### ISSUE TITLE
ERROR: cannot launch node of type [deoth_yolo/depth_combination.py]: deoth_yolo

### ISSUE THREAD

**Issue by leilei97** [0nhc/depth_yolo#1]
大佬您好，我想问下，出现下面这个ERROR，我要怎么解决，您遇到过这种情况吗
ERROR: cannot launch node of type [deoth_yolo/depth_combination.py]: deoth_yolo
ROS path [0]=/opt/ros/noetic/share/ros
ROS path [1]=/home/lei/catkin_ws/src
ROS path [2]=/opt/ros/noetic/share

**Comment by 0nhc** [comment]
emm不好意思这个项目我已经很久没动了，其实我使用了一个最低效的方法来实现的点云对齐，用的是PCL。其实应该直接用深度图来对齐的，只是后来我也懒得重新做了。。。如果有时间的话你可以自己把PCL读取点云换成直接读取深度图
